// Environment variables injected at build time
// This file is generated by GitHub Actions and should not be committed
// Generated: Tue Oct 28 18:24:26 UTC 2025

// Admin Credentials
window.ENV_GBTECH_USERNAME = 'GBTech';
window.ENV_GBTECH_PASSWORD = '1q2w3e!Q@W#E';
window.ENV_LARS_USERNAME = 'Lars';
window.ENV_LARS_PASSWORD = 'LarsHoney2025!';

// Firebase Configuration
window.ENV_FIREBASE_API_KEY = 'AIzaSyBLqjik76P7c72rgrMvo1lw86G3MOIIuNA';
window.ENV_FIREBASE_AUTH_DOMAIN = 'beemarshall-a311e.firebaseapp.com';
window.ENV_FIREBASE_DATABASE_URL = 'https://beemarshall-a311e-default-rtdb.firebaseio.com';
window.ENV_FIREBASE_PROJECT_ID = 'beemarshall-a311e';
window.ENV_FIREBASE_STORAGE_BUCKET = 'beemarshall-a311e.firebasestorage.app';
window.ENV_FIREBASE_MESSAGING_SENDER_ID = '502475319497';
window.ENV_FIREBASE_APP_ID = '1:502475319497:web:36e8120b0ca2c997870518';

// API Keys
window.ENV_GOOGLE_MAPS_API_KEY = '';
window.ENV_OPENWEATHER_API_KEY = '';
